name: NowTV M3U8 Fetcher

on:
  schedule:
    - cron: '*/1 * * * *'  # Her dakika çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-m3u8:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python nowtv.py

    - name: Commit and push if M3U8 changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add now.m3u8
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update M3U8 file" && git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git")
